version: "2.1"
services:
  plantuml:
    image: "plantuml/plantuml-server:jetty"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://plantuml:8080"]
      interval: 1s
      timeout: 1s
      retries: 15
  antora:
    image: "hauer/antora-plantuml"
    command: site.yml
    volumes:
       - ./:/antora
    depends_on:
      plantuml:
        condition: service_healthy
